FORMAT: 1A
HOST: https://roman-forum.herokuapp.com/

# roman-forum

roman-form is a simple API allowing consumers to manage topics and posts in a forum.

Please read the *Authentication* part before you 


# Data Structures

## TopicSimple
+ id: 42 (number)
+ title: Hello World (string)
+ posts_count: 1 (number)
+ inserted_at: `2016-10-26T03:37:51`
+ last_post_user_name: Ming
+ last_posted_at: `2016-10-26T03:37:51`

## PostItem
+ id: 100 (number)
+ content: "Some reply" (string)
+ post_user_name: "Ming" (string)
+ inserted_at: `2016-10-26T03:37:51`

## TopicDetail
+ id: 42 (number)
+ title: Hello World (string)
+ content: Content of this topic (string)
+ posts_count: 1 (number)
+ inserted_at: `2016-10-26T03:37:51`
+ last_post_user_name: Ming
+ last_posted_at: `2016-10-26T03:37:51`
+ posts (array[PostItem]) - A collection of post


## Registration [/api/register/]

### Register a User [POST]

Register a user throught the API. You should pass the user credentials in the http POST body, and
you will get a `jwt` token with expiration time.

+ Request (application/json)

        {
            "user":  {
              "name": "test_user_name",
              "password": "test_password"
            }
        }

        
+ Response 201 (applicaiton/json)

        {
            "jwt": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJVc2VyOjMiLCJleHAiOjE0ODAwNDY1NDQsImlhdCI6MTQ3NzQ1NDU0NCwiaXNzIjoiUm9tYW4iLCJqdGkiOiI2NTE3OTY5Ni1hMGEwLTRlMjctODExOS02NWMyY2NlZWNlNDEiLCJwZW0iOnt9LCJzdWIiOiJVc2VyOjMiLCJ0eXAiOiJhY2Nlc3MifQ.j2sxJbecY0clnjCGCC9NlRM_GERU8C8wdXSVzI6DDTrKqW0mjJCDZYLQh1XH0pdw_b5C99fz9TOb0K5h18O3Og",
            "exp": "32312111"
        }

## Login [/api/login/]

### Logig and get the token [POST]

Login the user to get the `jwt` token needed for `create`, `update` topics and posts

+ Request (application/json)

        {
            "user":  {
              "name": "test_user_name",
              "password": "test_password"
            }
        }

+ Response 201 (applicaiton/json)

        {
            "jwt": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJVc2VyOjMiLCJleHAiOjE0ODAwNDY1NDQsImlhdCI6MTQ3NzQ1NDU0NCwiaXNzIjoiUm9tYW4iLCJqdGkiOiI2NTE3OTY5Ni1hMGEwLTRlMjctODExOS02NWMyY2NlZWNlNDEiLCJwZW0iOnt9LCJzdWIiOiJVc2VyOjMiLCJ0eXAiOiJhY2Nlc3MifQ.j2sxJbecY0clnjCGCC9NlRM_GERU8C8wdXSVzI6DDTrKqW0mjJCDZYLQh1XH0pdw_b5C99fz9TOb0K5h18O3Og",
            "exp": "32312111"
        }


## Topics [/api/topics]

### List All Topics [GET]

+ Response 200 (application/json)

    + Attributes (array[TopicSimple])
    

### Create a New Topic [POST]

**You need to get a valid *jwt* token and put it in your http header when you create a topic.
To get a valid jwt token, please see the *Login* section.**

+ Request (application/json)

    + Headers

            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NzkyODIwOTQsImlhdCI6MTQ3NjY5MDA5NCwia2lkIjoiYTdlODllZDIxIiwidWlkIjoiNzExOTEzNjcwNSJ9.MTYupgkaiCw47YOiMUud6ksgqidBSlrOCXdJPqo87BX6-xkGjsbewwadOc7O3jriU8wQG-VhqILMsEWe6Hcvdjg3yiVsWiiPUwMotNHRuWqZQ-HupEoT7p_O_su2O9XFG38yLZl6oYtH7Y-pmNbqK0HIY3jxWLhietT1i7bX6c_mIROz4lJTO9cqYy0UntDGTDDmhfuWYT5zAsSzGXKodzh2Cyjy1octFFj-fTpR4t3bUUEcU8xC0PXn1ojrfzdtIzKxXPgExoyubacIcvkmAyNQNSaEqvpEwCJ8E5r7o6OgYgzhlGiK2Jd7tA_LAVs8F4R5_TKJre9tci9H

    + Body

            {
                "title": "Some nice title for the topic",
                "content": "Some nice content for the topic"
            }
            
+ Response 201 (application/json)

    + Body

            {
                "title": "Some nice title for the topic",
                "content": "Some nice content for the topic"
            }
        

## Topic [/api/topics/{topic_id}]

### Show a Topic [GET]

+ Parameters

    + topic_id - Unique id for this topic

+ Response 200 (application/json)

    + Attributes (array[TopicDetail])
        

### Update a Topic [PUT]
**You need to get a valid *jwt* token and put it in your http header when you create a topic.
To get a valid jwt token, please see the *Login* section.**

+ Request (application/json)

    + Headers

            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NzkyODIwOTQsImlhdCI6MTQ3NjY5MDA5NCwia2lkIjoiYTdlODllZDIxIiwidWlkIjoiNzExOTEzNjcwNSJ9.MTYupgkaiCw47YOiMUud6ksgqidBSlrOCXdJPqo87BX6-xkGjsbewwadOc7O3jriU8wQG-VhqILMsEWe6Hcvdjg3yiVsWiiPUwMotNHRuWqZQ-HupEoT7p_O_su2O9XFG38yLZl6oYtH7Y-pmNbqK0HIY3jxWLhietT1i7bX6c_mIROz4lJTO9cqYy0UntDGTDDmhfuWYT5zAsSzGXKodzh2Cyjy1octFFj-fTpR4t3bUUEcU8xC0PXn1ojrfzdtIzKxXPgExoyubacIcvkmAyNQNSaEqvpEwCJ8E5r7o6OgYgzhlGiK2Jd7tA_LAVs8F4R5_TKJre9tci9H
            
    + Body

            {
                "title": "Some nice title for the topic",
                "content": "Some nice content for the topic"
            }
            
    
+ Response 200 (application/json)

    + Body

            {
                "title": "Some nice title for the topic",
                "content": "Some nice content for the topic"
            }
            


## Posts [/{topic_id}/posts]


### Create a New Post [POST]

**You need to get a valid *jwt* token and put it in your http header when you create a topic.
To get a valid jwt token, please see the *Login* section.**


+ Parameters

    + topic_id - Unique id of the topic this post will be created with

+ Request (application/json)

    + Headers

            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NzkyODIwOTQsImlhdCI6MTQ3NjY5MDA5NCwia2lkIjoiYTdlODllZDIxIiwidWlkIjoiNzExOTEzNjcwNSJ9.MTYupgkaiCw47YOiMUud6ksgqidBSlrOCXdJPqo87BX6-xkGjsbewwadOc7O3jriU8wQG-VhqILMsEWe6Hcvdjg3yiVsWiiPUwMotNHRuWqZQ-HupEoT7p_O_su2O9XFG38yLZl6oYtH7Y-pmNbqK0HIY3jxWLhietT1i7bX6c_mIROz4lJTO9cqYy0UntDGTDDmhfuWYT5zAsSzGXKodzh2Cyjy1octFFj-fTpR4t3bUUEcU8xC0PXn1ojrfzdtIzKxXPgExoyubacIcvkmAyNQNSaEqvpEwCJ8E5r7o6OgYgzhlGiK2Jd7tA_LAVs8F4R5_TKJre9tci9H
        
    + Body
    
            {
                "post": {
                    "content": "some reply you want to create"
                }
            }

+ Response 201 (application/json)

    + Body

            {
                "id": 123
            }
            
## Post [/{topic_id}/posts/{post_id}]

### Update a Post [PUT]
**You need to get a valid *jwt* token and put it in your http header when you create a topic.
To get a valid jwt token, please see the *Login* section.**

+ Parameters

    + topic_id - Unique id for the topis this post is created with
    + post_id - Unique id for this post

+ Request (application/json)

    + Headers

            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NzkyODIwOTQsImlhdCI6MTQ3NjY5MDA5NCwia2lkIjoiYTdlODllZDIxIiwidWlkIjoiNzExOTEzNjcwNSJ9.MTYupgkaiCw47YOiMUud6ksgqidBSlrOCXdJPqo87BX6-xkGjsbewwadOc7O3jriU8wQG-VhqILMsEWe6Hcvdjg3yiVsWiiPUwMotNHRuWqZQ-HupEoT7p_O_su2O9XFG38yLZl6oYtH7Y-pmNbqK0HIY3jxWLhietT1i7bX6c_mIROz4lJTO9cqYy0UntDGTDDmhfuWYT5zAsSzGXKodzh2Cyjy1octFFj-fTpR4t3bUUEcU8xC0PXn1ojrfzdtIzKxXPgExoyubacIcvkmAyNQNSaEqvpEwCJ8E5r7o6OgYgzhlGiK2Jd7tA_LAVs8F4R5_TKJre9tci9H
        
    + Body
    
            {
                "post": {
                    "content": "some reply you want to create"
                }
            }

+ Response 200 (application/json)

    + Body

            {
                "id": 123
            }