FORMAT: 1A
HOST: https://roman-forum.herokuapp.com/

# roman-forum

roman-form is a simple API allowing consumers to manage topics and posts in a forum.

Some of the api needs authentication, please see the *Login* section if the endpoint needs authentication.

You can play with the real data in this website, it uses a demo built at https://roman-forum.herokuapp.com/

# Data Structures

## TopicSimple
+ id: 42 (number)
+ title: Hello World (string)
+ posts_count: 1 (number)
+ inserted_at: `2016-10-26T03:37:51`
+ last_post_user_name: Ming
+ last_posted_at: `2016-10-26T03:37:51`

## PostSimple
+ id: 100 (number)
+ content: "Some reply" (string)
+ inserted_at: `2016-10-26T03:37:51`
+ updated_at: `2016-10-26T03:37:51`
+ topic_id: 100

## PostItem
+ id: 100 (number)
+ content: "Some reply" (string)
+ post_user_name: "Ming" (string)
+ inserted_at: `2016-10-26T03:37:51`

## TopicDetail
+ id: 42 (number)
+ title: Hello World (string)
+ content: Content of this topic (string)
+ posts_count: 1 (number)
+ inserted_at: `2016-10-26T03:37:51`
+ last_post_user_name: Ming
+ last_posted_at: `2016-10-26T03:37:51`
+ posts (array[PostItem]) - A collection of post


## Registration [/api/register/]

### Register a User [POST]

Register a user throught the API. You should pass the user credentials in the http POST body, and
you will get a `jwt` token with expiration time.

The `jwt` token is used for authentication; you need to add the authentication header, for example:

`Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJVc2VyOjMiLCJleHAiOjE0ODAwNDY1NDQsImlhdCI6MTQ3NzQ1NDU0NCwiaXNzIjoiUm9tYW4iLCJqdGkiOiI2NTE3OTY5Ni1hMGEwLTRlMjctODExOS02NWMyY2NlZWNlNDEiLCJwZW0iOnt9LCJzdWIiOiJVc2VyOjMiLCJ0eXAiOiJhY2Nlc3MifQ.j2sxJbecY0clnjCGCC9NlRM_GERU8C8wdXSVzI6DDTrKqW0mjJCDZYLQh1XH0pdw_b5C99fz9TOb0K5h18O3Og` for endpoint that needs authentication.

+ Request (application/json)

        {
            "user":  {
              "name": "test_user_name",
              "password": "test_password"
            }
        }

        
+ Response 201 (applicaiton/json)

        {
            "jwt": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJVc2VyOjMiLCJleHAiOjE0ODAwNDY1NDQsImlhdCI6MTQ3NzQ1NDU0NCwiaXNzIjoiUm9tYW4iLCJqdGkiOiI2NTE3OTY5Ni1hMGEwLTRlMjctODExOS02NWMyY2NlZWNlNDEiLCJwZW0iOnt9LCJzdWIiOiJVc2VyOjMiLCJ0eXAiOiJhY2Nlc3MifQ.j2sxJbecY0clnjCGCC9NlRM_GERU8C8wdXSVzI6DDTrKqW0mjJCDZYLQh1XH0pdw_b5C99fz9TOb0K5h18O3Og",
            "exp": "32312111"
        }

## Login [/api/login/]

### Login and get the token [POST]

Login the user to get the `jwt` token.

The `jwt` token is used for authentication; you need to add the authentication header, for example:

`Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJVc2VyOjMiLCJleHAiOjE0ODAwNDY1NDQsImlhdCI6MTQ3NzQ1NDU0NCwiaXNzIjoiUm9tYW4iLCJqdGkiOiI2NTE3OTY5Ni1hMGEwLTRlMjctODExOS02NWMyY2NlZWNlNDEiLCJwZW0iOnt9LCJzdWIiOiJVc2VyOjMiLCJ0eXAiOiJhY2Nlc3MifQ.j2sxJbecY0clnjCGCC9NlRM_GERU8C8wdXSVzI6DDTrKqW0mjJCDZYLQh1XH0pdw_b5C99fz9TOb0K5h18O3Og` for endpoint that needs authentication.


+ Request (application/json)

        {
            "user":  {
              "name": "test_user_name",
              "password": "test_password"
            }
        }

+ Response 201 (applicaiton/json)

        {
            "jwt": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJVc2VyOjMiLCJleHAiOjE0ODAwNDY1NDQsImlhdCI6MTQ3NzQ1NDU0NCwiaXNzIjoiUm9tYW4iLCJqdGkiOiI2NTE3OTY5Ni1hMGEwLTRlMjctODExOS02NWMyY2NlZWNlNDEiLCJwZW0iOnt9LCJzdWIiOiJVc2VyOjMiLCJ0eXAiOiJhY2Nlc3MifQ.j2sxJbecY0clnjCGCC9NlRM_GERU8C8wdXSVzI6DDTrKqW0mjJCDZYLQh1XH0pdw_b5C99fz9TOb0K5h18O3Og",
            "exp": "32312111"
        }


## Topics [/api/topics]

### List All Topics [GET]

List all topics.

+ Response 200 (application/json)

    + Attributes (array[TopicSimple])
    

### Create a New Topic [POST]

Authentication required. Create a new topic.

+ Request (application/json)

    + Headers

            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NzkyODIwOTQsImlhdCI6MTQ3NjY5MDA5NCwia2lkIjoiYTdlODllZDIxIiwidWlkIjoiNzExOTEzNjcwNSJ9.MTYupgkaiCw47YOiMUud6ksgqidBSlrOCXdJPqo87BX6-xkGjsbewwadOc7O3jriU8wQG-VhqILMsEWe6Hcvdjg3yiVsWiiPUwMotNHRuWqZQ-HupEoT7p_O_su2O9XFG38yLZl6oYtH7Y-pmNbqK0HIY3jxWLhietT1i7bX6c_mIROz4lJTO9cqYy0UntDGTDDmhfuWYT5zAsSzGXKodzh2Cyjy1octFFj-fTpR4t3bUUEcU8xC0PXn1ojrfzdtIzKxXPgExoyubacIcvkmAyNQNSaEqvpEwCJ8E5r7o6OgYgzhlGiK2Jd7tA_LAVs8F4R5_TKJre9tci9H

    + Body

            {
                "title": "Some nice title for the topic",
                "content": "Some nice content for the topic"
            }
            
+ Response 201 (application/json)

    + Body
    
            + Attributes (TopicSimple)


## Topic [/api/topics/{topic_id}]

### Show a Topic [GET]

Show a topic's details including each post's information.

+ Parameters

    + topic_id - Unique id for this topic

+ Response 200 (application/json)

    + Attributes (array[TopicDetail])
        

### Update a Topic [PUT]

Authentication required. Update a topic's title or content.

+ Request (application/json)

    + Headers

            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NzkyODIwOTQsImlhdCI6MTQ3NjY5MDA5NCwia2lkIjoiYTdlODllZDIxIiwidWlkIjoiNzExOTEzNjcwNSJ9.MTYupgkaiCw47YOiMUud6ksgqidBSlrOCXdJPqo87BX6-xkGjsbewwadOc7O3jriU8wQG-VhqILMsEWe6Hcvdjg3yiVsWiiPUwMotNHRuWqZQ-HupEoT7p_O_su2O9XFG38yLZl6oYtH7Y-pmNbqK0HIY3jxWLhietT1i7bX6c_mIROz4lJTO9cqYy0UntDGTDDmhfuWYT5zAsSzGXKodzh2Cyjy1octFFj-fTpR4t3bUUEcU8xC0PXn1ojrfzdtIzKxXPgExoyubacIcvkmAyNQNSaEqvpEwCJ8E5r7o6OgYgzhlGiK2Jd7tA_LAVs8F4R5_TKJre9tci9H
            
    + Body

            {
                "title": "Some nice title for the topic",
                "content": "Some nice content for the topic"
            }
            
    
+ Response 200 (application/json)

    + Body

            + Attributes (TopicSimple)
            


## Posts [/{topic_id}/posts]


### Create a New Post [POST]

Authentication required. Create a new post (reply to a topic).


+ Parameters

    + topic_id - Unique id of the topic this post will be created with

+ Request (application/json)

    + Headers

            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NzkyODIwOTQsImlhdCI6MTQ3NjY5MDA5NCwia2lkIjoiYTdlODllZDIxIiwidWlkIjoiNzExOTEzNjcwNSJ9.MTYupgkaiCw47YOiMUud6ksgqidBSlrOCXdJPqo87BX6-xkGjsbewwadOc7O3jriU8wQG-VhqILMsEWe6Hcvdjg3yiVsWiiPUwMotNHRuWqZQ-HupEoT7p_O_su2O9XFG38yLZl6oYtH7Y-pmNbqK0HIY3jxWLhietT1i7bX6c_mIROz4lJTO9cqYy0UntDGTDDmhfuWYT5zAsSzGXKodzh2Cyjy1octFFj-fTpR4t3bUUEcU8xC0PXn1ojrfzdtIzKxXPgExoyubacIcvkmAyNQNSaEqvpEwCJ8E5r7o6OgYgzhlGiK2Jd7tA_LAVs8F4R5_TKJre9tci9H
        
    + Body
    
            {
                "post": {
                    "content": "some reply you want to create"
                }
            }

+ Response 201 (application/json)

    + Body
    
            + Attributes (PostSimple)

            
## Post [/{topic_id}/posts/{post_id}]

### Update a Post [PUT]

Authentication required. Update a post's content.

+ Parameters

    + topic_id - Unique id for the topis this post is created with
    + post_id - Unique id for this post

+ Request (application/json)

    + Headers

            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NzkyODIwOTQsImlhdCI6MTQ3NjY5MDA5NCwia2lkIjoiYTdlODllZDIxIiwidWlkIjoiNzExOTEzNjcwNSJ9.MTYupgkaiCw47YOiMUud6ksgqidBSlrOCXdJPqo87BX6-xkGjsbewwadOc7O3jriU8wQG-VhqILMsEWe6Hcvdjg3yiVsWiiPUwMotNHRuWqZQ-HupEoT7p_O_su2O9XFG38yLZl6oYtH7Y-pmNbqK0HIY3jxWLhietT1i7bX6c_mIROz4lJTO9cqYy0UntDGTDDmhfuWYT5zAsSzGXKodzh2Cyjy1octFFj-fTpR4t3bUUEcU8xC0PXn1ojrfzdtIzKxXPgExoyubacIcvkmAyNQNSaEqvpEwCJ8E5r7o6OgYgzhlGiK2Jd7tA_LAVs8F4R5_TKJre9tci9H
        
    + Body
    
            {
                "post": {
                    "content": "some reply you want to create"
                }
            }

+ Response 200 (application/json)

    + Body

            + Attributes (PostSimple)